create sequence hibernate_sequence start 1 increment 1;

create table message(
    id   int8 not null,
    text varchar(255),
    primary key (id)
);

create table permission
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table role
(
    id        int8 not null,
    role_name varchar(255),
    primary key (id)
);

create table role_permissions
(
    role_id        int8 not null,
    permissions_id int8 not null,
    primary key (role_id, permissions_id)
);

create table usr
(
    id       int8 not null,
    email    varchar(255),
    password varchar(255),
    status   varchar(255),
    username varchar(255),
    role_id  int8,
    primary key (id)
);

alter table if exists role_permissions add constraint
    role_permission_fk foreign key (permissions_id) references permission;

alter table if exists role_permissions add constraint
    permission_role_fk foreign key (role_id) references role;

alter table if exists usr add constraint
    usr_role_fk foreign key (role_id) references role;